name: web

on:
  push:
    paths:
      - ".github/workflows/web.yaml"
      - "web/**"

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install dependencies"
        run: npm ci
        working-directory: web
      - name: "Lint"
        run: npm run lint --if-present
        working-directory: web
      - name: "Build"
        run: npm run build:prod --if-present
        working-directory: web
      - name: "Test"
        run: npm run test --if-present
        working-directory: web

      - name: "dev: Build"
        run: npm run build:dev --if-present
        working-directory: web
      - name: "dev: Deploy"
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          external_repository: domdomegg/postal-vote-dev
          publish_dir: ./web/build

      - name: "prod: Build"
        run: npm run build:prod --if-present
        working-directory: web
      - name: "prod: Deploy"
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build
